require:
  - rubocop-rails

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.2.6
  TargetRailsVersion: 7.2
  Exclude:
    - '**/vendor/**/*'
    - '**/db/schema.rb'
    - '**/db/migrate'
    - '**/app/views/**/*'


##################### Style ##################################

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

##################### Metrics ##################################

Layout/LineLength:
  Max: 110

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

##################### Rails ##################################

Rails:
  Enabled: true
